### ISSUE TITLE
Audio out of sync - using FFMPEG branch

### ISSUE THREAD

**Issue by dorgan** [nebhead/PlexPostProc#4]

**Comment by nebhead** [comment]
Hmm... probably an FFMPEG issue.  I was running into the same type of issue with HandBrake which is why I switched to FFMPEG.  Have you tried different video players?  Do you experience the same audio sync issues consistently?  I have noticed that sometimes I will have the issue with direct play on Plex Web but not on Roku, Android or just playing with VLC.

**Comment by dorgan** [comment]
This is the first time I have had this issue.  Ultimately I have been trying to use Don Melton’s transcode-video ruby gem, which uses handbrake but it throws errors so I have tried yours.  I haven’t tried the handbrake branch.  I will switch to that and see what happens

**Comment by nebhead** [comment]
@dorgan - Do you mind if I close this one?  I am guessing your issue is probably with FFMPEG, but let me know.
